### ISSUE TITLE
make.py in Genetic-Algorithm-for-Synopses-Generator/implementation/synopses_generator/ requires the presence of a "target" folder.

### ISSUE THREAD

**Issue by aizazulhaq** [GiannisFikioris/Genetic-Algorithm-for-Synopses-Generator#4]
make.py in Genetic-Algorithm-for-Synopses-Generator/implementation/synopses_generator/ requires the presence of a "target" folder. The folder is not created automatically

**Comment by GiannisFikioris** [comment]
Good observation! Fixed with the latest commit.
